"""Regenerate flights/transform_dbt/main.py by embedding the dbt/ project.

Run this after any change under dbt/ and then push the result to the
transform Flight with update_flight (source_code=<new main.py contents>).
"""
import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DBT_DIR = REPO_ROOT / "dbt"
OUT_PATH = REPO_ROOT / "flights" / "transform_dbt" / "main.py"

SKIP_DIRS = {"target", "dbt_packages", "logs"}

TEMPLATE = '''"""MotherDuck Flight: run the f1 dbt project (`dbt build`) against md:f1.

Auto-generated by scripts/generate_transform_flight.py — do not hand-edit the
FILES dict. Re-run the generator after changing anything under dbt/, then
push the result via update_flight.
"""
import pathlib
import subprocess

PROJECT_DIR = pathlib.Path("/tmp/dbt_project")

FILES = {files!r}


def main():
    for rel_path, content in FILES.items():
        path = PROJECT_DIR / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    subprocess.run(
        ["dbt", "build", "--project-dir", str(PROJECT_DIR), "--profiles-dir", str(PROJECT_DIR)],
        check=True,
    )


if __name__ == "__main__":
    main()
'''


def main():
    files = {}
    for path in sorted(DBT_DIR.rglob("*")):
        if path.is_dir():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        rel = path.relative_to(DBT_DIR).as_posix()
        files[rel] = path.read_text()

    OUT_PATH.write_text(TEMPLATE.format(files=files))
    print(f"Wrote {OUT_PATH} embedding {len(files)} dbt project files:")
    for rel in files:
        print(f"  - {rel}")


if __name__ == "__main__":
    main()
